# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: "https://registry.npmjs.org"
      env:
        NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
    - uses: pnpm/action-setup@v2
      with:
          version: latest
    - run: pnpm i
    - run: mv ./node_modules/@babel/parser node_modules_babel_parser
    - run: pnpm run build
    - run: pnpm test && pnpm tsc --build --clean
    - run: mv node_modules_babel_parser ./node_modules/@babel/parser
    - run: pnpm view "ember-template-tag@$(cat package.json | jq -r '.version')" || npm publish
      if: github.ref == 'refs/heads/main'
    
